version: '3.8'

networks:
   tunnel-119x:
      ipam:
         driver: default
         config:
            - subnet: 172.18.0.0/27
            # 172.18.0.0 - 172.18.0.31

#   tunnel-1195:
#     ipam:
#        driver: default
#        config:
#           - subnet: 10.13.14.0/24
#   tunnel-1196:
#      ipam:
#         driver: default
#         config:
#            - subnet: 10.14.15.0/24

   postgres:
      ipam:
         driver: default
         config:
            - subnet: 172.18.0.32/27
            # 172.18.0.32 - 172.18.0.63
   client:
      ipam:
         driver: default
         config:
            - subnet: 172.18.0.64/27
            # 172.18.0.64 - 172.18.0.95
   keycloak:
      ipam:
         driver: default
         config:
            - subnet: 172.18.0.96/27
            # 172.18.0.96 - 172.18.0.127
   mongo:
      ipam:
         driver: default
         config:
            - subnet: 172.18.0.128/27
            # 172.18.0.128 - 172.18.0.159
   rocketchat:
      ipam:
         driver: default
         config:
            - subnet: 172.18.0.160/27
            # 172.18.0.160 - 172.18.0.191

# 2 untapped subnets(total 8 subnets, 6 subnets used):
# 172.18.0.192 - 172.18.0.223
# 172.18.0.224 - 172.18.0.255

#   peerjs:
#      driver: bridge

services:
   tunnel-1194:
      image: c6supper/galaxy-tunnel:${TUNNEL_TAG}
      container_name: galaxy-tunnel-1194
      cap_add:
         - NET_ADMIN
      devices:
         - "/dev/net/tun"
      networks:
         - tunnel-119x
         - client
         - keycloak
#         - peerjs
         - rocketchat
         - postgres
      #volumes:
      #   - ${TUNNEL_1194_GALAXY_VOLUME}:${TUNNEL_LOG_DIR}
      restart: ${APP_RESTART_POLICY}
      environment:
         RUN_AFTER_SIDECAR: 'no'
         OVPN_PORT: 1194
         OVPN_PROTO: tcp
         OVPN_IP_POOL: 10.0.0.0
         OVPN_TLS_AUTH: ta.key
         OVPN_CA: ca.crt
         OVPN_CERT: server1.crt
         OVPN_KEY: server1.key
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}
      ports:
         - "1194:1194"
         - "80:80"
         - "443:443"
         - "1195:1195"
         - "1196:1196"

   tunnel-1195:
      image: c6supper/galaxy-tunnel:${TUNNEL_TAG}
      container_name: galaxy-tunnel-1195
      cap_add:
         - NET_ADMIN
      devices:
         - "/dev/net/tun"
      network_mode: service:tunnel-1194
      #volumes:
      #   - ${TUNNEL_1195_GALAXY_VOLUME}:${TUNNEL_LOG_DIR}
      restart: ${APP_RESTART_POLICY}
      environment:
         RUN_AFTER_SIDECAR: 'no'
         OVPN_PORT: 1195
         OVPN_PROTO: tcp
         OVPN_IP_POOL: 10.13.13.0
         OVPN_TLS_AUTH: longterm/ta.key
         OVPN_CA: longterm/ca.crt
         OVPN_CERT: longterm/server2.crt
         OVPN_KEY: longterm/server2.key
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   tunnel-1196:
      image: c6supper/galaxy-tunnel:${TUNNEL_TAG}
      container_name: galaxy-tunnel-1196
      cap_add:
         - NET_ADMIN
      devices:
         - "/dev/net/tun"
      network_mode: service:tunnel-1194
      #volumes:
      #   - ${TUNNEL_1196_GALAXY_VOLUME}:${TUNNEL_LOG_DIR}
      restart: ${APP_RESTART_POLICY}
      environment:
         RUN_AFTER_SIDECAR: 'no'
         OVPN_PORT: 1196
         OVPN_PROTO: tcp
         OVPN_IP_POOL: 10.14.14.0
         OVPN_TLS_AUTH: longterm/ta.key
         OVPN_CA: longterm/ca.crt
         OVPN_CERT: longterm/server3.crt
         OVPN_KEY: longterm/server3.key
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   #nginx:
      #image: c6supper/galaxy-nginx:${NGINX_TAG}
      #container_name: galaxy-nginx
      ## network_mode: ${APP_NETWORK_MODE}
      #restart: ${APP_RESTART_POLICY}
      #environment:
         #GALAXY_TUNNEL_HOST: galaxy-tunnel-1194
         #GALAXY_CLIENT_HOST: galaxy-client
      #depends_on:
         #- client
         #- tunnel-1194
         #- keycloak
      #network_mode: service:tunnel-1194
      ##volumes:
      ##   - ${NGINX_GALAXY_VOLUME}:${NGINX_LOG_DIR}
      #logging:
         #driver: ${APP_LOGGING_DRIVER}
         #options:
            #max-size: ${APP_LOGGING_SIZE}
            #max-file: ${APP_LOGGING_NUMBER}

   openresty:
      image: c6supper/galaxy-openresty:${OPENRESTY_TAG}
      container_name: galaxy-openresty
      restart: ${APP_RESTART_POLICY}
      environment:
         GALAXY_TUNNEL_HOST: ${TUNNEL_HOST}
         GALAXY_CLIENT_HOST: ${CLIENT_HOST}
         GALAXY_KEYCLOAK_HOST: ${KEYCLOAK_HOST}
         GALAXY_CLIENT_DB: ${CLIENT_DB}
         GALAXY_OPENRESTY_RESOLVER: ${OPENRESTY_RESOLVER}
         GALAXY_POSTGRES_HOST: ${POSTGRES_HOST}
         GALAXY_POSTGRES_USER: ${APP_POSTGRES_USER}
         GALAXY_POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
         GALAXY_OPENRESTY_USER: ${OPENRESTY_USER}
         GALAXY_OPENRESTY_PASSWORD: ${OPENRESTY_PASSWORD}
      depends_on:
         - client
         - tunnel-1194
         - keycloak
         - rocketchat
         - postgres
      network_mode: service:tunnel-1194
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}


   client:
      image: c6supper/galaxy-client:${CLIENT_TAG}
      container_name: galaxy-client
      # network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      depends_on:
         - postgres
      networks:
         - postgres
         - client
      volumes:
         - ${CLIENT_GALAXY_VOLUME}:${CLIENT_LOG_DIR}
      environment:
         GALAXY_GUACD_HOST: ${GUACD_HOST}
         GALAXY_POSTGRES_HOST: ${POSTGRES_HOST}
         GALAXY_POSTGRES_DB: ${APP_POSTGRES_DB}
         GALAXY_POSTGRES_USER: ${APP_POSTGRES_USER}
         GALAXY_POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
         GALAXY_CLIENT_DB: ${CLIENT_DB}
         GALAXY_CLIENT_USER: ${CLIENT_USER}
         GALAXY_CLIENT_PASSWORD: ${CLIENT_PASSWORD}
         GALAXY_CLIENT_LOG_DIR: ${CLIENT_LOG_DIR}
         GALAXY_AUTH_URL: ${GALAXY_AUTH_URL}
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}
      ports:
         - "8000:8000"

   guacd:
      image: c6supper/galaxy-guacd:${GUACD_TAG}
      container_name: galaxy-guacd
      # network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      network_mode: service:tunnel-1194
      depends_on:
         - tunnel-1194
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   postgres:
      image: postgres:${POSTGRES_TAG}
      container_name: galaxy-postgres
      # network_mode: ${APP_NETWORK_MODE}
      restart: ${APP_RESTART_POLICY}
      environment:
         POSTGRES_USER: ${APP_POSTGRES_USER}
         POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
         POSTGRES_DB: ${APP_POSTGRES_DB}
      networks:
         - postgres
      volumes:
         - ${POSTGRES_DATA_VOLUME}:/var/lib/postgresql/data
      stop_grace_period: 2m
      stop_signal: SIGINT
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}
      ports:
         - ${POSTGRES_PORT}:${POSTGRES_PORT}

   adminer:
      image: adminer
      restart: always
      container_name: galaxy-postgres-adminer
      networks:
         - postgres
         - mongo
      ports:
         - 8081:8080

   keycloak-init:
      image: c6supper/galaxy-keycloak-init:${KEYCLOAK_INIT_TAG}
      container_name: galaxy-keycloak-init
      restart: always
      environment:
         KEYCLOAK_DB: ${KEYCLOAK_DB}
         KEYCLOAK_DB_USER: ${KEYCLOAK_DB_USER}
         KEYCLOAK_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
         GALAXY_POSTGRES_HOST: ${POSTGRES_HOST}
         GALAXY_POSTGRES_USER: ${APP_POSTGRES_USER}
         GALAXY_POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
         GALAXY_POSTGRES_PORT: ${POSTGRES_PORT}
      depends_on:
         - postgres
      networks:
         - keycloak
         - postgres
#      volumes:
#         - ${KEYCLOAK_INIT_LOG_VOLUME}:${KEYCLOAK_INIT_LOG_DIR}
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}

   keycloak:
      image: c6supper/galaxy-keycloak:${KEYCLOAK_TAG}
      container_name: galaxy-keycloak
      restart: always
      environment:
         PROXY_ADDRESS_FORWARDING: "true"
         DB_VENDOR: postgres
         DB_PORT: ${POSTGRES_PORT}
         KEYCLOAK_USER: ${KEYCLOAK_USER}
         KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
         DB_ADDR: galaxy-postgres
         DB_DATABASE: ${KEYCLOAK_DB}
         DB_USER: ${KEYCLOAK_DB_USER}
         DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
         KEYCLOAK_LOGLEVEL: DEBUG
         KEYCLOAK_IMPORT: ${KEYCLOAK_REALM_FILE}
      #         JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
#         JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
      depends_on:
         - keycloak-init
#      network_mode: service:keycloak-init
      networks:
         - keycloak
         - postgres
#      volumes:
#         - ${KEYCLOAK_GALAXY_VOLUME}:/galaxy
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}
      ports:
         - ${KEYCLOAK_HTTP_PORT}:${KEYCLOAK_HTTP_PORT}

   mongo:
      image: mongo:${MONGO_TAG}
      container_name: galaxy-mongo
      restart: ${APP_RESTART_POLICY}
#      environment:
#         MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
#         MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      networks:
         - mongo
      volumes:
         - ${MONGO_DATA_VOLUME}:/data/db
      command: mongod --smallfiles --oplogSize 128 --replSet rs0 --storageEngine=mmapv1
      stop_grace_period: 2m
      logging:
         driver: ${APP_LOGGING_DRIVER}
         options:
            max-size: ${APP_LOGGING_SIZE}
            max-file: ${APP_LOGGING_NUMBER}
      ports:
         - ${MONGO_PORT}:${MONGO_PORT}
      labels:
         - "traefik.enable=false"

   mongo-init-replica:
      image: mongo:${MONGO_TAG}
      container_name: galaxy-mongo-init-replica
      networks:
         - mongo
      command: >
         bash -c
           "for i in `seq 1 30`; do
             mongo mongo/rocketchat --eval \"
               rs.initiate({
                 _id: 'rs0',
                 members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
             s=$$? && break || s=$$?;
             echo \"Tried ${DOLLAR}${DOLLAR}i times. Waiting 5 secs...\";
             sleep 5;
           done; (exit ${DOLLAR}${DOLLAR}s)"
      depends_on:
         - mongo

   rocketchat:
      image: rocket.chat:${ROCKETCHAT_TAG}
      container_name: galaxy-rocketchat
      # equivalent to docker run --init, solve the node in process 1, doesn't response for SIGTERM
      init: true
      networks:
         - mongo
         - rocketchat
         - keycloak
      command: >
         bash -c
           "for i in `seq 1 30`; do
             node --inspect=0.0.0.0 main.js &&
             s=$$? && break || s=$$?;
             echo \"Tried ${DOLLAR}${DOLLAR}i times. Waiting 5 secs...\";
             sleep 5;
           done; (exit ${DOLLAR}${DOLLAR}s)"
      restart: ${APP_RESTART_POLICY}
      extra_hosts:
         - ${APP_DEBUG_SERVER_URL}:${APP_DEBUG_SERVER_HOST}
      volumes:
#         - ${CLIENT_GALAXY_VOLUME}:${CLIENT_LOG_DIR}
         - ${ROCKETCHAT_UPLOAD_VOLUME}:/app/uploads
      environment:
         - PORT=${ROCKETCHAT_PORT}
         - ROOT_URL=${ROCKETCHAT_ROOT_URL}/chat/
         - MONGO_URL=mongodb://galaxy-mongo:${MONGO_PORT}/rocketchat
         - MONGO_OPLOG_URL=mongodb://galaxy-mongo:${MONGO_PORT}/local
         - MAIL_URL=smtp://smtp.email
         - ADMIN_USERNAME=${ROCKETCHAT_ADMIN_USERNAME}
         - ADMIN_PASS=${ROCKETCHAT_ADMIN_PASS}
         - ADMIN_EMAIL=${ROCKETCHAT_ADMIN_EMAIL}
         - OVERWRITE_SETTING_Site_Url=${ROCKETCHAT_ROOT_URL}/chat/
         - OVERWRITE_SETTING_Show_Setup_Wizard=completed
         - Language=en
         - Accounts_OAuth_Custom-Keycloak=true
         - Accounts_OAuth_Custom-Keycloak-url=${ROCKETCHAT_ROOT_URL}/keycloak/auth
         - Accounts_OAuth_Custom-Keycloak-token_path=/realms/VeEX/protocol/openid-connect/token
         - Accounts_OAuth_Custom-Keycloak-token_sent_via=header
         - Accounts_OAuth_Custom-Keycloak-identity_token_sent_via=header
         - Accounts_OAuth_Custom-Keycloak-identity_path=/realms/VeEX/protocol/openid-connect/userinfo
         - Accounts_OAuth_Custom-Keycloak-authorize_path=/realms/VeEX/protocol/openid-connect/auth
         - Accounts_OAuth_Custom-Keycloak-scope=openid
         - Accounts_OAuth_Custom-Keycloak-id=EZRemote
         - Accounts_OAuth_Custom-Keycloak-login_style=redirect
         - Accounts_OAuth_Custom-Keycloak-button_label_text=Login via Keycloak
         - Accounts_OAuth_Custom-Keycloak-button_label_color="#FFFFFF"
         - Accounts_OAuth_Custom-Keycloak-button_color="#13679A"
         - Accounts_OAuth_Custom-Keycloak-username_field=preferred_username
         - Accounts_OAuth_Custom-Keycloak-merge_users=true
         - Accounts_OAuth_Custom-Keycloak-access_token_param=access_token
         - Iframe_Integration_send_enable=true
         - Iframe_Integration_receive_enable=true
      stop_grace_period: 2m
      depends_on:
         - mongo
      ports:
         - ${ROCKETCHAT_PORT}:${ROCKETCHAT_PORT}
      labels:
         - "traefik.backend=rocketchat"
         - "traefik.frontend.rule=Host: ${ROCKETCHAT_ROOT_URL}/chat/"

#   peerjs:
#      image: c6supper/galaxy-peerjs:${PEERJS_TAG}
#      container_name: galaxy-peerjs
#      restart: ${APP_RESTART_POLICY}
#      networks:
#         - peerjs
#      logging:
#         driver: ${APP_LOGGING_DRIVER}
#         options:
#            max-size: ${APP_LOGGING_SIZE}
#            max-file: ${APP_LOGGING_NUMBER}